### ISSUE TITLE
Problème d'importation de données Keycloak avec un fichier monté via Docker (version 26.1.0)

### ISSUE THREAD

**Issue by Rbtsv2** [Rbtsv2/poc-traefik-keycloak-oauth2-web-php#1]
Description :
Avec la version 26.1.0 de Keycloak, l'importation de données à partir d'un fichier JSON monté via Docker échoue systématiquement. Le fichier est correctement lié au conteneur via un volume, mais l'importation ne fonctionne pas. Ce problème semble être lié à une modification récente dans la gestion des imports ou des permissions.

Étapes pour reproduire :
    Créer un fichier d'export JSON (par exemple realm-export.json).
    Configurer un conteneur Docker Keycloak avec un volume pour monter ce fichier et activer l'importation :
  
```
version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: ["start", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
```
    
Démarrer le conteneur avec docker-compose up.
Observer les logs pour constater l'échec de l'importation.
